### PR TITLE
readme: add that katriawm is available on the AUR

### PR DESCRIPTION
**Pull request by tmplt**
https://aur.archlinux.org/packages/katriawm/

### CODE REVIEW

**Comment by vain** [comment]
Hi,

thanks!

1.  Could you just put the URL in the README, instead of suggesting one particular tool? I don't use pacaur which means that if this tool vanishes or changes its syntax or something like that, I won't notice. A simple URL is more generic (and pacaur users will still know what to do).
2.  katriawm is configured by editing config.h files. Your PKGBUILD should pick them up if they exist. Here are some examples on how you could do it:
    -   https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dwm-git
    -   https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xiate-git

Cheers

**Comment by Tmplt** [comment]
I'll make sure to fix this tomorrow, at latest. Do you want me to squash the commits?

**Comment by tmplt** [comment]
The AUR package has been updated. The custom `config.h` is used if it is in `${SRCDEST}/${pkgname}/`.

Do you want me to squash the commits?

**Comment by vain** [comment]
> Do you want me to squash the commits?

No, it's fine this way. :)

I'll go ahead and merge this. Thanks!

You might want to think about picking up the second config.h as well. There are two of them: One in `core/` and one in `barinfo/`.

**Comment by tmplt** [comment]
Oops, missed that one.
 
I'm not aware of any directory hierarchy consensus when it comes to custom header files. Should `${SRCDEST}/katriawm/{katriawm.barinfo}.h` be looked for, or should I mirror the directory tree of the repo (`${SRCDEST}/katriawm/src/{core,barinfo}config.h`) instead?

**Comment by vain** [comment]
Hmm, in my dotfiles, I use `katriawm-config.h` and `katriabi-config.h`. I guess that would work in your PKGBUILD as well.

**Comment by tmplt** [comment]
Ah, so that's how people apply settings for compile-time stuff.

`prepare()` now apply `${XDG_CONFIG_HOME}/katria{wm,bi}-config.h` if they exist.

**Comment by vain** [comment]
Oh, that's an interesting idea (reading files directly from `~/.config`). I thought about putting them in `$srcdir`, but reading them from `~/.config` saves some extra work.

I don't know if this follows Arch's package guidelines. I feel like packages should not pick up files outside of the PKGBUILD's directory, but you would have to ask the Arch guys about that, if you want to be sure.

**Pull request merged**
