### PR TITLE
Spawn floating windows under mouse

### PR DESCRIPTION
**Pull request by CamilleScholtz**
See title. Sorry for the test commit :)

### CODE REVIEW

**Comment by vain** [comment]
Hmm, I'll have to use that for a while to see if it works for me.

(Yes, this could be added as an optional mode and then be configured in `config.h`. Problem is, if I don't use it, then I'll have a hard time maintaining the code. One of my guidelines is that I try to include only those features that I really use on a daily basis in order to avoid rotting code. I guess the best way to handle this situation would be to establish a "patch culture", like dwm has.)

**Comment by CamilleScholtz** [comment]
No problem, if you don't like it I'll just create some personal patch repo.

**Comment by vain** [comment]
For the time being, that'd be the best option, I guess. But I'll still give it a try. :)

If, for some reason, more and more pull requests come up, I could also create a `katriawm-contrib` repo to collect those patches (similar to http://dwm.suckless.org/patches/). That repo would also be a good place to collect contributed themes.

**Comment by vain** [comment]
I don't think this model works for me.

It felt nice/interesting at first, but here's the thing: I rarely use floating mode and I like to not touch the mouse for longer periods of time. This means I keep forgetting the pointer's location. %) When a floating window spawns, it appears in a seemingly random location. That feels very confusing.

**Pull request closed without merging**
